<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBF9hOBa\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBF9hOBa/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBF9hOBa.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBF9hOBa\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBF9hOBa\App_KernelProdContainer([
    'container.build_hash' => 'BF9hOBa',
    'container.build_id' => '67a6774d',
    'container.build_time' => 1652429243,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBF9hOBa');
