<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'main_page' => [[], ['_controller' => 'App\\Controller\\MainPageController::index'], [], [['text', '/']], [], [], []],
    'realizations' => [[], ['_controller' => 'App\\Controller\\RealizationsController::realizations'], [], [['text', '/realizacje']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::contact'], [], [['text', '/kontakt']], [], [], []],
];
