<?php

namespace ContainerBF9hOBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainPageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MainPageController' shared autowired service.
     *
     * @return \App\Controller\MainPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MainPageController'] = $instance = new \App\Controller\MainPageController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\MainPageController', $container));

        return $instance;
    }
}
