<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItn1C0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItn1C0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItn1C0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItn1C0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItn1C0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'Itn1C0R',
    'container.build_id' => 'd88f88e7',
    'container.build_time' => 1654242143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItn1C0R');
