<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtR4DBZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtR4DBZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPtR4DBZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPtR4DBZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPtR4DBZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PtR4DBZ',
    'container.build_id' => '5660fbe9',
    'container.build_time' => 1654032553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtR4DBZ');
